apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  namespace: test-alb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: email
      type: backe-end
  template:
    metadata:
      labels:
        app: email
        type: backe-end
    spec:
      containers:
        - name: email-service
          image: leonardorothier/email-service:v1
          ports:
            - containerPort: 8080
          env:
            - name: GMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gmail-credentials
                  key: username
            - name: GMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gmail-credentials
                  key: password