apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: test-nlb
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: email-site
    type: back-end